### ISSUE TITLE
there's an error i wasn't able to solve 

### ISSUE THREAD

**Issue by HallaDernouni** [ncorbuk/Python-Motion-Detection-system#3]
in "for c in cnt:"
TypeError: 'NoneType' object is not iterable

**Comment by gitservice-daniel** [comment]
Did you solve it? I couldn't solve it too.

**Comment by gh-purplerain** [comment]
Which camera do you use=? I think I found the error.

**Comment by HallaDernouni** [comment]
Hey I just solved the error, you just need to change the [1] in line 57 to [0]
